### ISSUE TITLE
Add a link to the data?

### ISSUE THREAD

**Issue by Cghlewis** [shannonpileggi/rmedicine-data-cleaning-2023#55]
Now that the recording of the session is up on YouTube, I see that people are requesting access to the "messy_uc.xlsx" file. Do you think we should add a link to the file (https://github.com/shannonpileggi/rmedicine-data-cleaning-2023/blob/main/data/messy_uc.xlsx) under "The Data" on the "Exercises" page?

**Comment by shannonpileggi** [comment]
thanks for catching this, done!
